import { assert, assertEquals } from 'https://deno.land/std@0.224.0/assert/mod.ts'
import { SITE_RESEARCH_ALERT_PREFIX, notifySiteResearch, siteResearchBotToken } from './alerts.ts'
import { type ClaimedRun, runOneIteration, type WorkerDb } from './iteration.ts'
import { buildRequestParams, containerErrorMessage, type CreateFn, hasCodeExecutionArtifacts, type ModelResponse, requestOnce } from './loop.ts'

// Run 623d15e7, iteration 1, as the API returned it (block shapes from the stored convo and the
// 2026-09-15 live probe): web searches run INSIDE a code-execution container, then a direct
// client tool call in the same turn.
const CONTAINER = 'container_01VmZUVGE4tq7SCWzo68nDN1'
const SEARCH_THEN_GEOCODE: ModelResponse = {
  stop_reason: 'tool_use',
  container: { id: CONTAINER, expires_at: '2026-09-15T17:58:17.722710Z' },
  usage: { input_tokens: 1000, output_tokens: 200, server_tool_use: { web_search_requests: 8 } },
  content: [
    { type: 'server_tool_use', id: 'srvtoolu_ce1', name: 'code_execution', input: {} },
    { type: 'server_tool_use', id: 'srvtoolu_ws1', name: 'web_search', input: { query: 'Navicent address' }, caller: { type: 'code_execution_20260120', tool_id: 'srvtoolu_ce1' } },
    { type: 'web_search_tool_result', tool_use_id: 'srvtoolu_ws1', content: [], caller: { type: 'code_execution_20260120', tool_id: 'srvtoolu_ce1' } },
    { type: 'code_execution_tool_result', tool_use_id: 'srvtoolu_ce1', content: {} },
    { type: 'tool_use', id: 'toolu_geo1', name: 'geocode_address', input: { address: '777 Hemlock St, Macon, GA 31201' }, caller: { type: 'direct' } },
  ],
}

/** The exact rejection the API gives when that turn is resumed without the container. */
const MISSING_CONTAINER_400 = Object.assign(
  new Error('400 {"type":"error","error":{"type":"invalid_request_error","message":"container_id is required when there are pending tool uses generated by code execution with tools."}}'),
  { status: 400 },
)

/** A DB fake that behaves like the RPCs: committed convo and container carry to the next claim. */
function engine() {
  const run: ClaimedRun = {
    id: 'run1', thread_id: 't1', kind: 'archetype', target_seq: 0, prompt_template_id: 'tpl', iteration: 0, attempt: 1,
    convo: [{ role: 'user', content: 'go' }], search_budget: 12, web_search_requests: 0, web_search_locked: false,
    site_submit_id: 'ss1', pinned_context: {}, container_id: null,
  }
  const log: string[] = []
  const finalized: string[] = []
  const db: WorkerDb = {
    claim: () => Promise.resolve({ ...run, convo: [...run.convo] }),
    recordResponse: (a) => { run.web_search_requests += a.webSearchRequests; return Promise.resolve(true) },
    recordToolResult: () => Promise.resolve(true),
    completeStep: (a) => {
      run.convo = a.convo; run.iteration++
      run.container_id = a.containerId ?? run.container_id // COALESCE, as in complete_thread_run_step
      log.push(`commit container=${a.containerId ?? '-'}`)
      return Promise.resolve(true)
    },
    finalize: (a) => { finalized.push(a.content); return Promise.resolve({ status: 'finalized' as const }) },
    release: (_r, _o, _i, _a, e) => { log.push(`release:${e}`); return Promise.resolve() },
    fail: (_r, e) => { log.push(`fail:${e}`); return Promise.resolve() },
    promptBody: () => Promise.resolve('SYSTEM'),
  }
  return { run, db, log, finalized }
}

const deps = (db: WorkerDb, create: CreateFn) => ({
  db, create, log: () => {}, chain: () => Promise.resolve(),
  execute: () => Promise.resolve({ match: { match_quality: 'exact' }, distance_miles: 7.9 }),
  clientTools: [{ name: 'geocode_address' }], webSearchTool: { type: 'web_search_20260209', name: 'web_search' },
})

Deno.test('regression 623d15e7: searches in a container, then a client tool, then resume — resume carries the container', async () => {
  const { run, db, log, finalized } = engine()
  const requests: Array<Record<string, unknown>> = []
  const create: CreateFn = (params) => {
    requests.push(params)
    if (requests.length === 1) return Promise.resolve(SEARCH_THEN_GEOCODE)
    // Resume: behave like the API — reject when the pending code-execution turn has no container.
    if (params.container !== CONTAINER) return Promise.reject(MISSING_CONTAINER_400)
    return Promise.resolve({ stop_reason: 'end_turn', usage: {}, content: [{ type: 'text', text: 'Report.' }] })
  }

  assertEquals(await runOneIteration('run1', 'w1', deps(db, create)), 'chained')
  assertEquals(requests[0].container, undefined) // nothing to resume on the first request
  assertEquals(run.container_id, CONTAINER)      // committed with the conversation

  // The resume is a separate worker invocation: only what was committed survives.
  assertEquals(await runOneIteration('run1', 'w2', deps(db, create)), 'finalized')
  assertEquals(requests[1].container, CONTAINER)
  assertEquals(finalized, ['Report.'])
  assertEquals(log, [`commit container=${CONTAINER}`])
})

Deno.test('the pre-fix behaviour reproduces the failure (guards the fake itself)', async () => {
  const { db, log } = engine()
  let n = 0
  const create: CreateFn = (params) => {
    n++
    if (n === 1) return Promise.resolve({ ...SEARCH_THEN_GEOCODE })
    delete params.container // simulate the old loop, which never sent it
    return Promise.reject(MISSING_CONTAINER_400)
  }
  await runOneIteration('run1', 'w1', deps(db, create))
  assertEquals(await runOneIteration('run1', 'w2', deps(db, create)), 'failed')
  assert(log[1].startsWith('fail:code_execution_container_missing'), log[1])
})

Deno.test('a later response with no container keeps sending the earlier one', async () => {
  const { run, db } = engine()
  const sent: unknown[] = []
  const responses: ModelResponse[] = [
    SEARCH_THEN_GEOCODE,
    { stop_reason: 'tool_use', usage: {}, content: [{ type: 'tool_use', id: 'toolu_geo2', name: 'geocode_address', input: {}, caller: { type: 'direct' } }] },
    { stop_reason: 'end_turn', usage: {}, content: [{ type: 'text', text: 'done' }] },
  ]
  const create: CreateFn = (p) => { sent.push(p.container); return Promise.resolve(responses.shift()!) }
  for (let i = 0; i < 3; i++) await runOneIteration('run1', `w${i}`, deps(db, create))
  assertEquals(sent, [undefined, CONTAINER, CONTAINER])
  assertEquals(run.container_id, CONTAINER)
})

Deno.test('an expired or unknown container fails the run with a clear message, not a raw 400', async () => {
  const { run, db, log } = engine()
  run.container_id = 'container_gone'
  run.iteration = 1
  const create: CreateFn = () => Promise.reject(Object.assign(new Error('404 {"type":"error","error":{"type":"not_found_error","message":"Container container_gone not found"}}'), { status: 404 }))
  assertEquals(await runOneIteration('run1', 'w', deps(db, create)), 'failed')
  assert(log[0].startsWith('fail:code_execution_container_unavailable: the code-execution container for this run (container_gone)'), log[0])
  assert(log[0].includes('Retry the run'))
})

Deno.test('containerErrorMessage ignores errors that are not about the container', () => {
  assertEquals(containerErrorMessage(Object.assign(new Error('529 overloaded'), { status: 529 }), 'c'), null)
  assertEquals(containerErrorMessage(Object.assign(new Error('400 max_tokens too large'), { status: 400 }), 'c'), null)
  assert(containerErrorMessage(MISSING_CONTAINER_400, null)!.startsWith('code_execution_container_missing'))
})

Deno.test('site research alerts: always prefixed; separate bot when configured, else the shared bot', async () => {
  const env = (vars: Record<string, string>) => ({ get: (k: string) => vars[k] })
  assertEquals(siteResearchBotToken(env({ SITE_RESEARCH_TELEGRAM_BOT_TOKEN: 'own', TELEGRAM_BOT_TOKEN: 'claw' })), { token: 'own', bot: 'site_research' })
  assertEquals(siteResearchBotToken(env({ TELEGRAM_BOT_TOKEN: 'claw' })), { token: 'claw', bot: 'shared_openclaw' })
  const calls: Array<{ url: string; text: string }> = []
  const fakeFetch = ((url: string, init: RequestInit) => {
    calls.push({ url, text: JSON.parse(String(init.body)).text })
    return Promise.resolve(new Response('{}', { status: 200 }))
  }) as unknown as typeof fetch
  await notifySiteResearch('❌ Site research run x failed', fakeFetch, env({ TELEGRAM_BOT_TOKEN: 'claw' }) as never)
  assertEquals(calls[0].url, 'https://api.telegram.org/botclaw/sendMessage')
  assert(calls[0].text.startsWith(SITE_RESEARCH_ALERT_PREFIX + '\n❌ Site research run x failed'))
})

// ---------------------------------------------------------------------------
// Runs abf8c06f / 2b170116 (2026-09-16): budget spent at 12/12, web_search dropped, container still
// sent -> 400 "Container identifier can only be provided when using the code execution tool".
// ---------------------------------------------------------------------------
const WEB_SEARCH = { type: 'web_search_20260209', name: 'web_search' }
const CONTAINER_WITHOUT_TOOL_400 = Object.assign(
  new Error('400 {"type":"error","error":{"type":"invalid_request_error","message":"container: Container identifier can only be provided when using the code execution tool"}}'),
  { status: 400 },
)
/** The committed turn of run abf8c06f: searches run inside code execution, then direct client tools. */
const CODE_EXEC_TURN = [
  { type: 'server_tool_use', id: 'ce1', name: 'code_execution', input: {} },
  { type: 'server_tool_use', id: 'ws1', name: 'web_search', input: {}, caller: { type: 'code_execution_20260120', tool_id: 'ce1' } },
  { type: 'web_search_tool_result', tool_use_id: 'ws1', content: [], caller: { type: 'code_execution_20260120', tool_id: 'ce1' } },
  { type: 'code_execution_tool_result', tool_use_id: 'ce1', content: {} },
  { type: 'tool_use', id: 'g1', name: 'geocode_address', input: {}, caller: { type: 'direct' } },
]
const exhausted = (convo: Array<Record<string, unknown>>, containerId: string | null) => {
  const sent: Array<Record<string, unknown>> = []
  const create: CreateFn = (p) => { sent.push(p); return Promise.resolve({ stop_reason: 'end_turn', usage: {}, content: [{ type: 'text', text: 'ok' }] }) }
  return requestOnce({
    create, baseParams: { model: 'm' }, convo, clientTools: [{ name: 'geocode_address' }], webSearchTool: WEB_SEARCH,
    searchBudget: 12, searchesUsed: 12, dropRejected: false, containerId, log: () => {},
  }).then(() => sent[0])
}

Deno.test('hasCodeExecutionArtifacts: the container-bearing turn shapes', () => {
  assert(hasCodeExecutionArtifacts(CODE_EXEC_TURN))
  assert(hasCodeExecutionArtifacts([{ type: 'web_search_tool_result', caller: { type: 'code_execution_20260120' } }]))
  assert(!hasCodeExecutionArtifacts([{ type: 'text', text: 'hi' }, { type: 'tool_use', name: 'geocode_address', caller: { type: 'direct' } }]))
  assert(!hasCodeExecutionArtifacts(undefined))
})

Deno.test('regression abf8c06f: budget spent on a code-execution turn keeps web_search declared AND the container', async () => {
  const params = await exhausted([{ role: 'user', content: 'go' }, { role: 'assistant', content: CODE_EXEC_TURN },
    { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'g1', content: '{}' }] }], CONTAINER)
  const tools = params.tools as Array<Record<string, unknown>>
  assertEquals(tools.some((t) => t.name === 'web_search'), true)       // declared, so the container is legal
  assertEquals(params.tool_choice, { type: 'none' })                    // ...but no new search can start
  assertEquals(params.container, CONTAINER)
})

Deno.test('budget spent with no code execution in the turn: no web_search and NO container', async () => {
  const params = await exhausted([{ role: 'user', content: 'go' },
    { role: 'assistant', content: [{ type: 'tool_use', id: 'g1', name: 'geocode_address', input: {}, caller: { type: 'direct' } }] },
    { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'g1', content: '{}' }] }], CONTAINER)
  assertEquals((params.tools as Array<Record<string, unknown>>).some((t) => t.name === 'web_search'), false)
  assertEquals(params.container, undefined)
  assertEquals(params.tool_choice, undefined)
})

Deno.test('invariant: a dropped web_search never carries a container', () => {
  for (const plan of [{ mode: 'drop' as const }, { mode: 'lock' as const }, { mode: 'search' as const, maxUses: 3 }]) {
    const p = buildRequestParams({ model: 'm' }, [{ role: 'user', content: 'x' }], [{ name: 'geocode_address' }], WEB_SEARCH, plan, CONTAINER)
    const declared = ((p.tools ?? []) as Array<Record<string, unknown>>).some((t) => t.name === 'web_search')
    assertEquals(p.container !== undefined, declared, `plan ${plan.mode}`)
  }
  // No web search tool at all (a phase that never searches): container is never sent.
  assertEquals(buildRequestParams({ model: 'm' }, [], [], null, { mode: 'drop' }, CONTAINER).container, undefined)
})

Deno.test('containerErrorMessage: "can only be provided" is a request-shape bug, not an expired container', () => {
  const m = containerErrorMessage(CONTAINER_WITHOUT_TOOL_400, CONTAINER)!
  assert(m.startsWith('code_execution_container_without_tool'), m)
  assert(m.includes('not an expired'), m)
  assert(!m.includes('code_execution_container_unavailable'))
  // The genuine cases keep their own labels.
  assert(containerErrorMessage(MISSING_CONTAINER_400, CONTAINER)!.startsWith('code_execution_container_missing'))
  assert(containerErrorMessage(Object.assign(new Error('404 {"error":{"message":"Container container_x not found"}}'), { status: 404 }), CONTAINER)!
    .startsWith('code_execution_container_unavailable'))
})
