-- Code-execution container continuity for site research runs.
--
-- web_search_20260209 filters results by running code in a code-execution container. When a
-- turn that ran code there continues with client tool results, the API requires the
-- container id on the next request ("container_id is required when there are pending tool
-- uses generated by code execution with tools"). Run 623d15e7 failed on exactly that: 8
-- searches, then geocode_address in the same turn, then the resume 400'd.
--
-- The container id arrives on each response (container.id). It is committed WITH the
-- conversation it belongs to (complete_thread_run_step), returned by claim_thread_run, and
-- sent as the top-level `container` request parameter on the next iteration. A deep pass
-- phase change starts a new conversation, so it clears the id.
--
-- claim_thread_run, advance_thread_run_phase and complete_thread_run_step are rebuilt from
-- their LIVE definitions (pg_get_functiondef, 2026-09-15).

ALTER TABLE public.research_thread_run
  ADD COLUMN container_id text,
  ADD COLUMN container_expires_at timestamptz;

COMMENT ON COLUMN public.research_thread_run.container_id IS
  'Anthropic code-execution container of the committed conversation (response container.id); sent as `container` on the next request.';
COMMENT ON COLUMN public.research_thread_run.container_expires_at IS
  'container.expires_at from the response that set container_id. Diagnostic only: Anthropic documents it as a shorter rolling value, not a hard limit.';

-- complete_thread_run_step gains the container. Signature changes, so drop and recreate.
DROP FUNCTION public.complete_thread_run_step(uuid, uuid, integer, integer, jsonb, integer, boolean);

CREATE FUNCTION public.complete_thread_run_step(
  p_run_id uuid, p_owner uuid, p_iteration integer, p_attempt integer, p_convo jsonb,
  p_client_tool_calls integer, p_web_search_locked boolean,
  p_container_id text DEFAULT NULL, p_container_expires_at timestamptz DEFAULT NULL)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  UPDATE research_thread_run
     SET convo = p_convo, iteration = iteration + 1, attempts = 0,
         client_tool_calls = client_tool_calls + p_client_tool_calls,
         web_search_locked = web_search_locked OR p_web_search_locked,
         -- A response without a container (no code ran this turn) keeps the earlier one:
         -- the conversation still contains that container's blocks.
         container_id = COALESCE(p_container_id, container_id),
         container_expires_at = CASE WHEN p_container_id IS NOT NULL THEN p_container_expires_at ELSE container_expires_at END,
         lease_owner = NULL, lease_expires_at = NULL, heartbeat_at = now()
   WHERE id = p_run_id AND lease_owner = p_owner AND iteration = p_iteration AND state = 'running';
  IF NOT FOUND THEN RETURN false; END IF;
  UPDATE research_thread_run_step SET outcome = 'committed', finished_at = now()
   WHERE run_id = p_run_id AND iteration = p_iteration AND attempt = p_attempt;
  RETURN true;
END;
$function$;

REVOKE ALL ON FUNCTION public.complete_thread_run_step(uuid, uuid, integer, integer, jsonb, integer, boolean, text, timestamptz) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.complete_thread_run_step(uuid, uuid, integer, integer, jsonb, integer, boolean, text, timestamptz) TO service_role;

CREATE OR REPLACE FUNCTION public.advance_thread_run_phase(
  p_run_id uuid, p_owner uuid, p_iteration integer, p_attempt integer,
  p_next_phase text, p_convo jsonb, p_prompt_template_id uuid, p_phase_search_budget integer,
  p_state_patch jsonb, p_client_tool_calls integer DEFAULT 0)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_next_phase NOT IN ('school_fill', 'deep_pass', 'exports') THEN
    RAISE EXCEPTION 'invalid next phase %', p_next_phase;
  END IF;
  IF p_phase_search_budget < 0 THEN RAISE EXCEPTION 'negative phase search budget'; END IF;

  UPDATE research_thread_run
     SET pass_phase = p_next_phase,
         convo = p_convo,
         prompt_template_id = COALESCE(p_prompt_template_id, prompt_template_id),
         phase_state = phase_state || COALESCE(p_state_patch, '{}'::jsonb),
         phase_search_base = web_search_requests,
         search_budget = web_search_requests + p_phase_search_budget,
         phase_iteration_base = iteration + 1,
         web_search_locked = false,  -- the new conversation has no search blocks in it
         container_id = NULL, container_expires_at = NULL,  -- ...and no code execution to resume
         client_tool_calls = client_tool_calls + COALESCE(p_client_tool_calls, 0),
         iteration = iteration + 1, attempts = 0,
         lease_owner = NULL, lease_expires_at = NULL, heartbeat_at = now()
   WHERE id = p_run_id AND lease_owner = p_owner AND iteration = p_iteration
     AND state = 'running' AND kind = 'deep_pass';
  IF NOT FOUND THEN RETURN false; END IF;

  UPDATE research_thread_run_step SET outcome = 'committed', finished_at = now()
   WHERE run_id = p_run_id AND iteration = p_iteration AND attempt = p_attempt;
  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.claim_thread_run(p_run_id uuid, p_owner uuid, p_lease_seconds integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_run     research_thread_run%ROWTYPE;
  v_thread  research_thread%ROWTYPE;
  v_retry   numeric(10,6);
  v_attempt int;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(p_run_id::text, 1));
  SELECT * INTO v_run FROM research_thread_run WHERE id = p_run_id FOR UPDATE;
  IF NOT FOUND OR v_run.state NOT IN ('queued', 'running') THEN RETURN NULL; END IF;
  IF v_run.lease_owner IS NOT NULL AND v_run.lease_expires_at > now() THEN RETURN NULL; END IF;

  -- Any attempt still 'in_progress' at this iteration belongs to a worker that
  -- died. Its cost is already on the run (recorded at response time); account it
  -- as retry cost and mark it discarded.
  WITH d AS (
    UPDATE research_thread_run_step
       SET outcome = 'discarded', finished_at = COALESCE(finished_at, now()),
           error = COALESCE(error, 'worker died or lease expired before this attempt committed')
     WHERE run_id = p_run_id AND iteration = v_run.iteration AND outcome = 'in_progress'
    RETURNING cost_usd
  )
  SELECT COALESCE(sum(cost_usd), 0) INTO v_retry FROM d;

  IF v_run.attempts >= v_run.max_attempts THEN
    UPDATE research_thread_run
       SET state = 'failed', finished_at = now(), lease_owner = NULL, lease_expires_at = NULL,
           retry_cost_usd = retry_cost_usd + v_retry,
           error = COALESCE(error, format('gave up after %s attempts at iteration %s', v_run.attempts, v_run.iteration))
     WHERE id = p_run_id;
    PERFORM recompute_research_thread_state(v_run.thread_id);
    RETURN NULL;
  END IF;

  v_attempt := v_run.attempts + 1;
  UPDATE research_thread_run
     SET state = 'running', phase = 'researching', attempts = v_attempt,
         lease_owner = p_owner, lease_expires_at = now() + make_interval(secs => p_lease_seconds),
         heartbeat_at = now(), started_at = COALESCE(started_at, now()),
         retry_cost_usd = retry_cost_usd + v_retry
   WHERE id = p_run_id
  RETURNING * INTO v_run;

  INSERT INTO research_thread_run_step (run_id, iteration, attempt) VALUES (p_run_id, v_run.iteration, v_attempt);
  PERFORM recompute_research_thread_state(v_run.thread_id);
  SELECT * INTO v_thread FROM research_thread WHERE id = v_run.thread_id;

  RETURN jsonb_build_object(
    'id', v_run.id, 'thread_id', v_run.thread_id, 'kind', v_run.kind, 'target_seq', v_run.target_seq,
    'prompt_template_id', v_run.prompt_template_id, 'iteration', v_run.iteration, 'attempt', v_attempt,
    'max_attempts', v_run.max_attempts,
    'convo', v_run.convo, 'search_budget', v_run.search_budget,
    'web_search_requests', v_run.web_search_requests, 'web_search_locked', v_run.web_search_locked,
    'pass_phase', v_run.pass_phase, 'phase_state', v_run.phase_state,
    'container_id', v_run.container_id,
    'phase_iteration_base', v_run.phase_iteration_base, 'phase_search_base', v_run.phase_search_base,
    'site_submit_id', v_thread.site_submit_id, 'pinned_context', v_thread.pinned_context,
    'archetype_primary', v_thread.archetype_primary, 'archetype_secondary', v_thread.archetype_secondary,
    'story_carriers', to_jsonb(v_thread.story_carriers));
END;
$function$;
